export const tasks2 = [
  { id: 1, title: 'りんごを買う', done: false },
  { id: 2, title: 'サバを買う', done: false },
  { id: 3, title: 'JavaScriptを勉強する', done: false },
  { id: 4, title: 'Vueを勉強する', done: false },
  { id: 5, title: '豚肉を買う', done: false },
  { id: 6, title: 'ほうれん草を買う', done: false },
  { id: 7, title: 'うなぎを買う', done: false },
  { id: 8, title: 'Reactを勉強する', done: false },
  { id: 9, title: '人参を買う', done: false },
  { id: 10, title: '薬を買う', done: false },
  { id: 11, title: 'Angularを勉強する', done: false },
  { id: 12, title: 'CSSを勉強する', done: false },
  { id: 13, title: '切手を買う', done: false },
  { id: 14, title: 'パソコンを買う', done: false },
  { id: 15, title: '定期券を買う', done: false },
  { id: 16, title: 'デザインを勉強する', done: false },
  { id: 17, title: '色を勉強する', done: false },
  { id: 18, title: 'プログラミングを勉強する', done: false },
  { id: 19, title: 'phpを勉強する', done: false },
  { id: 20, title: 'Javaを勉強する', done: false },
];
export const tasks = [
  { id: 1, title: '野菜を買う', done: false },
  { id: 2, title: '魚を買う', done: false },
  { id: 3, title: 'JavaScriptの勉強をする', done: false },
  { id: 4, title: '原稿を書く', done: false },
];
